name: CI

on:
    push:
        branches:
            - main
            - master
jobs:
    build-and-push:
        name: 'Build and Push'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # uma vez que o docker nao tem o go instalado, ele pega uma imagem a partir da 1.22 para vc rodar testes e outras coisas que precisem do Go dentro da pipe
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22.x'

            - name: Run unit Tests
              run: go test

            - name: Generate SHA
              id: generate_sha
              # 7 primeiros caracteres do sha
              # centraliza a saida dos dados: GITHUB_OUTPUT
              run: |
                  SHA=$(echo $GITHUB_SHA | head -c7)
                  echo "sha=$SHA" >> $GITHUB_OUTPUT

            - name: Login into the container
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      melinski/nlw-journey-go_api:${{steps.generate_sha.outputs.sha}}
                      melinski/nlw-journey-go_api:latest
            # - name: Build Docker Image
            #   run: docker build -t melinski/nlw-journey-go_api:${{steps.generate_sha.outputs.sha}} .
            # - name: Push Image
            #   run: docker push melinski/nlw-journey-go_api:${{steps.generate_sha.outputs.sha}}
